### PR TITLE
plz pull

### PR DESCRIPTION
**Pull request by ghost**
:)

### CODE REVIEW

**Comment by macaullyjames** [comment]
Could you add some more of you favourite things to patrik.txt before I pull? :)

**Comment by ghost** [comment]
Sure!
Do I need to update this pull request once I've pushed the requested changes to the fork? :)

**Comment by macaullyjames** [comment]
Nope, just push the changes and it'll show up in the PR.

**Comment by ghost** [comment]
Done and done! :)

**Comment by macaullyjames** [comment]
Fantastic! :+1: I would have pulled it sooner, but I was in a tunnel (strange how Arlanda, the most connected place in Sweden, has no 3G coverage...) ^^

It's not important now, but next time remember to branch off of _develop_. Never, ever branch off of _master_. Ever.

Nice job! :)

**Pull request merged**
